- name: Demo of variables
  hosts: all
  vars:
    URL: manish.google.com
  vars_files:
    - vars.yml
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
    - name: print variable from task
      debug:
        msg: URL = {{URL}}
      vars:
        URL: tak.google.com