- name: Demo of variables
  hosts: all
  vars:
    URL: manish.google.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
  tasks:
    - name: print variable from task
      debug:
        msg: URL = {{URL}}
      vars:
        URL: tak.google.com