- name: Demo of variables
  hosts: all
  vars_files:
      - vars.yml
  vars:
    URL: manish.google.com
  tasks:
    - name: print variable
      debug:
        msg: URL = {{URL}}
    - name: print variable from task
      debug:
        msg: URL = {{URL}}
      vars:
        URL: tak.google.com
    - name: print a varaiable from inventory
      debug:
        msg: URL == {{URL}} , URL1 = {{URL1}}
- name: runtime variables
  hosts: all
  tasks:
    - name: run uptime command
      shell: uptime
      register: out

    - name: print variable
      debug:
        msg: "{{out}}"


